customer: "seyi-assessment"
region: "eu=west-1"
vpc_cidr: "10.0.0.0/16"

ec2_instance:
  name: asg-demo
  ami_id: null
  port: 80
  type: "t3.small"
  scaling_cpu: 60.0
  min_size: 1
  max_size: 3
  desired_size:  1

alb_scaling:
  enabled: true
  request_count: 1000

tags:
  Customer: seyi

